zookeeper:
    image: zookeeper
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    # Currently, this cannot be scaled dynamically. It must be odd and > 3 for quorum to be maintained
    replicas: 1
    # Use this to set the resources available to each zookeeper container
    resources: {}

solr:
    image: cedadev/esgf-solr
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each solr container
    resources: {}

postgres:
    image: cedadev/esgf-postgres
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    # Use this to set the resources available to the postgres container
    resources: {}

indexNode:
    image: cedadev/esgf-index-node
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}
    # Configuration for Solr collections
    # Must have maxShardsPerNode >= (numShards * replicationFactor) / replicas
    solrCollections:
      # Number of shards to use for Solr collections
      mumShards: 1
      # Replication factor to use for Solr collections
      replicationFactor: 1
      # Maximum number of shards allowed per node for a given collection
      maxShardsPerNode: 1

idpNode:
    image: cedadev/esgf-idp-node
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}

orp:
    image: cedadev/esgf-orp
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}

tds:
    image: cedadev/esgf-tds
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}

cog:
    image: cedadev/esgf-cog
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}

auth:
    image: cedadev/esgf-auth
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}
    # The postgres for use by esgf-auth
    postgres:
      image: postgres
      imageTag: 10
      # imagePullPolicy: "IfNotPresent"
      resources: {}

slcs:
    image: cedadev/esgf-slcs
    imageTag: latest
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    # Use this to set the resources available to each index node container
    resources: {}
    # The postgres for use by the SLCS
    postgres:
      image: postgres
      imageTag: 10
      # imagePullPolicy: "IfNotPresent"
      resources: {}

proxy:
  image: cedadev/esgf-proxy
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
