solr:
  image: esgfhub/solr
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  # Use this to set the resources available to each solr container
  master:
    resources: {}
    persistence:
      # Set this to true to use a PVC with the following properties
      enabled: false
      # storageClass: ""
      size: 10Gi
      selector: {}
  slave:
    resources: {}
    persistence:
      # Set this to true to use a PVC with the following properties
      enabled: false
      # storageClass: ""
      size: 10Gi
      selector: {}

postgres: &postgresImage
  image: esgfhub/postgres
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"

postgresEsgcet:
  image: esgfhub/postgres-esgcet
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  # Use this to set the resources available to the postgres-esgcet container
  resources: {}
  persistence:
    # Set this to true to use a PVC with the following properties
    enabled: false
    # storageClass: ""
    size: 10Gi
    selector: {}

indexNode:
  image: esgfhub/index-node
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}

idpNode:
  image: esgfhub/idp-node
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}

orp:
  image: esgfhub/orp
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}

tds:
  image: esgfhub/tds
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
  data:
    # storageClass: ""
    size: 10Gi
    selector: {}
  content:
    # storageClass: ""
    size: 10Gi
    selector: {}

cog:
  image: esgfhub/cog
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
  # The postgres used by CoG
  postgres:
    <<: *postgresImage
    resources: {}
    persistence:
      # Set this to true to use a PVC with the following properties
      enabled: false
      # storageClass: ""
      size: 10Gi
      selector: {}

auth:
  image: esgfhub/auth
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
  # The postgres for use by esgf-auth
  postgres:
    <<: *postgresImage
    resources: {}
    persistence:
      # Set this to true to use a PVC with the following properties
      enabled: false
      # storageClass: ""
      size: 10Gi
      selector: {}

slcs:
  image: esgfhub/slcs
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
  # The postgres for use by the SLCS
  postgres:
    <<: *postgresImage
    resources: {}
    persistence:
      # Set this to true to use a PVC with the following properties
      enabled: false
      # storageClass: ""
      size: 10Gi
      selector: {}

proxy:
  image: esgfhub/proxy
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  replicas: 1
  # Use this to set the resources available to each index node container
  resources: {}
  ingressMode: kubernetes

publisher:
  image: esgfhub/publisher
  imageTag: latest
  # imagePullPolicy: "IfNotPresent"
  resources: {}
