apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-slcs-secrets"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: slcs
data:
  slcs-database-password: "{{ index .Values.secrets "slcs-database-password" | b64enc }}"
  slcs-secret-key: "{{ index .Values.secrets "slcs-secret-key" | b64enc }}"
