# Headless service providing a network domain for the stateful set
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-zk"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: zookeeper
spec:
  ports:
    - name: follower
      port: 2888
    - name: leader-election
      port: 3888
  clusterIP: None
  selector:
    release: {{ .Release.Name }}
    component: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-zk"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: zookeeper
spec:
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: zookeeper
  # This is the service for the network domain
  serviceName: "{{ .Release.Name }}-zk"
  # Currently, this cannot be scaled dynamically. It must be odd and > 3 for quorum to be maintained
  replicas: 3
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          volumeMounts:
            - name: zk-data
              mountPath: /data
            - name: zk-datalog
              mountPath: /datalog
          env:
            - name: ZOO_REPLICAS
              value: "3"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "5"
          # Currently, the statefulset ordinal is not available independently
          # of the hostname, so we need to rip it out
          # We also build the server list using 0.0.0.0 as the address of the current
          # server to avoid port binding errors due to the DNS entry not being ready
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -e
              export ZOO_MY_ID="${HOSTNAME##*-}"
              ZOO_SERVERS=""
              for i in $(seq 0 $(($ZOO_REPLICAS - 1))); do
                if [[ "$i" = "$ZOO_MY_ID" ]]; then
                  ZOO_SERVERS="$ZOO_SERVERS server.$i=0.0.0.0:2888:3888"
                else
                  ZOO_SERVERS="$ZOO_SERVERS server.$i={{ .Release.Name }}-zk-$i.{{ .Release.Name }}-zk:2888:3888"
                fi
              done
              export ZOO_SERVERS
              env
              exec /docker-entrypoint.sh zkServer.sh start-foreground
          # For readiness and liveness, check that the node is running using the ruok 4 letter word
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ruok | nc 127.0.0.1 2181 | grep imok"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "echo ruok | nc 127.0.0.1 2181 | grep imok"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: zk-data
          emptyDir: {}
        - name: zk-datalog
          emptyDir: {}
