{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.persistence.storageClass | default "" | quote }}
  resources:
{{ toYaml .Values.postgres.persistence.resources | indent 4 }}
{{- if .Values.postgres.persistence.selector }}
{{ toYaml .Values.postgres.persistence.selector | indent 2 }}
{{- end }}
---
{{- end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-postgres"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: postgres
spec:
  replicas: 1
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: postgres
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: postgres
      annotations:
        checksum/postgres-secrets: {{ include (print $.Template.BasePath "/postgres/secret.yaml") . | sha256sum }}
        checksum/cog-secrets: {{ include (print $.Template.BasePath "/cog/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}"
          imagePullPolicy: {{ default "" .Values.postgres.imagePullPolicy | quote }}
          ports:
            - name: postgres
              containerPort: 5432
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe:
            tcpSocket: &probe
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: DBSUPER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgres-secrets"
                  key: "database-password"
            - name: ESGCET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgres-secrets"
                  key: database-publisher-password
            - name: ESGF_ROOTADMIN_EMAIL
              value: "CoG@{{ .Values.hostname }}"
            - name: ESGF_ROOTADMIN_USERNAME
              value: rootAdmin
            - name: ESGF_ROOTADMIN_OPENID
              value: https://{{ .Values.hostname }}/esgf-idp/openid/rootAdmin
            - name: ESGF_ROOTADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-cog-secrets"
                  key: rootadmin-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
      volumes:
        - name: postgres-data
{{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-postgres"
{{- else }}
          emptyDir: {}
{{- end }}
