apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgres"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: postgres
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    release: {{ .Release.Name }}
    component: postgres
