apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-trust-bundle"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: certificates
data:
  esg-trust-bundle.pem: |-
{{ index .Values.certificates "esg-trust-bundle.pem" | indent 4 }}
