apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-solr"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: solr
spec:
  replicas: {{ .Values.solr.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: solr
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: solr
    spec:
      initContainers:
        # Wait for zookeeper to become available before starting
        - name: ensure-zookeeper
          image: busybox
          command:
            # Try every 5 seconds for no longer than 10 mins
            - sh
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if echo stat | nc -w 1 "{{ .Release.Name }}-zookeeper" 2181 | grep -q Zxid; then exit 0; fi
              done
              exit 1
      containers:
        - name: solr
          image: "{{ .Values.solr.image }}:{{ .Values.solr.imageTag }}"
          imagePullPolicy: {{ default "" .Values.solr.imagePullPolicy | quote }}
          ports:
            - name: solr
              containerPort: 8983
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe:
            tcpSocket: &probe
              port: 8983
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: SOLR_HOME
              value: /esg/solr-home
            - name: SOLR_HEAP
              value: 1g
            - name: ZOOKEEPER_HOST
              value: "{{ .Release.Name }}-zookeeper"
          args:
            - "solr-foreground"
            - "-c"
            - "-p"
            - "8983"
            - "-z"
            - "$(ZOOKEEPER_HOST):2181"
            - "-s"
            - "$(SOLR_HOME)"
          volumeMounts:
            - name: solr-home
              mountPath: /esg/solr-home
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: solr-home
          emptyDir: {}
