apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-tds"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: tds
spec:
  ports:
    - name: http
      port: 8080
  selector:
    release: {{ .Release.Name }}
    component: tds
