{{- if .Values.cog.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
    cog-role: database
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.cog.postgres.persistence.storageClass }}
  storageClassName: "{{ .Values.cog.postgres.persistence.storageClass }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.cog.postgres.persistence.size }}
  selector:
{{ toYaml .Values.cog.postgres.persistence.selector | indent 4 }}
---
{{- end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-postgres-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
    cog-role: database
spec:
  replicas: 1
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: cog
      cog-role: database
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: cog
        cog-role: database
      annotations:
        checksum/postgres-esgcet-secrets: {{ include (print $.Template.BasePath "/postgres-esgcet/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: postgres-cog
          image: "{{ .Values.cog.postgres.image }}:{{ .Values.cog.postgres.imageTag }}"
          imagePullPolicy: {{ default "" .Values.cog.postgres.imagePullPolicy | quote }}
          ports:
            - name: postgres
              containerPort: 5432
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe:
            tcpSocket: &probe
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: POSTGRESQL_DATABASE
              value: cogdb
            - name: POSTGRESQL_USER
              value: dbsuper
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgres-esgcet-secrets"
                  key: "database-password"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
{{ toYaml .Values.cog.postgres.resources | indent 12 }}
      volumes:
        - name: postgres-data
{{- if .Values.cog.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-postgres-cog"
{{- else }}
          emptyDir: {}
{{- end }}
