apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-cog-secrets"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
data:
  rootadmin-password: "{{ index .Values.secrets "rootadmin-password" | b64enc }}"
  cog-secret-key: "{{ index .Values.secrets "cog-secret-key" | b64enc }}"
