apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-cog"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: cog
spec:
  ports:
    - name: http
      port: 8000
  selector:
    release: {{ .Release.Name }}
    component: cog
