apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-auth"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: auth
    auth-role: frontend
spec:
  replicas: {{ .Values.auth.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: auth
      auth-role: frontend
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: auth
        auth-role: frontend
      annotations:
        checksum/auth-secrets: {{ include (print $.Template.BasePath "/auth/secret.yaml") . | sha256sum }}
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/certificates/trust-bundle-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        # Wait for postgres to become available before starting
        - name: ensure-postgres
          image: "{{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}"
          imagePullPolicy: {{ default "" .Values.postgres.imagePullPolicy | quote }}
          env:
            - name: PGHOST
              value: "{{ .Release.Name }}-postgres-auth"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: authuser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth-secrets"
                  key: "auth-database-password"
            - name: PGDATABASE
              value: auth
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
      containers:
        - name: auth
          image: "{{ .Values.auth.image }}:{{ .Values.auth.imageTag }}"
          imagePullPolicy: {{ default "" .Values.auth.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8000
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe:
            httpGet: &probe
              path: /esgf-auth/home/
              port: 8000
              # The ALLOWED_HOSTS setting means that the app will only accept
              # requests from the correct host
              httpHeaders:
                - name: Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Host
                  value: "{{ .Values.hostname }}"
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: ESGF_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: ESGF_DATABASE_HOST
              value: "{{ .Release.Name }}-postgres-esgcet"
            # ESGF-Auth settings
            - name: SCRIPT_NAME
              value: /esgf-auth
            - name: ESGF_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth-secrets"
                  key: "auth-secret-key"
            - name: ESGF_COOKIE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth-secrets"
                  key: "shared-cookie-secret-key"
            # Database settings
            - name: DJANGO_DATABASE_DEFAULT_ENGINE
              value: django.db.backends.postgresql
            - name: DJANGO_DATABASE_DEFAULT_HOST
              value: "{{ .Release.Name }}-postgres-auth"
            - name: DJANGO_DATABASE_DEFAULT_PORT
              value: "5432"
            - name: DJANGO_DATABASE_DEFAULT_USER
              value: authuser
            - name: DJANGO_DATABASE_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth-secrets"
                  key: "auth-database-password"
            - name: DJANGO_DATABASE_DEFAULT_NAME
              value: auth
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          resources:
{{ toYaml .Values.auth.resources | indent 12 }}
      volumes:
        - name: trust-bundle
          configMap:
            name: "{{ .Release.Name }}-trust-bundle"
