apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-auth-secrets"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: auth
data:
  auth-database-password: "{{ index .Values.secrets "auth-database-password" | b64enc }}"
  auth-secret-key: "{{ index .Values.secrets "auth-secret-key" | b64enc }}"
  shared-cookie-secret-key: "{{ index .Values.secrets "shared-cookie-secret-key" | b64enc }}"
