apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-index-node"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: index-node
spec:
  replicas: {{ .Values.indexNode.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: index-node
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: index-node
    spec:
      containers:
        - name: index-node
          image: "{{ .Values.indexNode.image }}:{{ .Values.indexNode.imageTag }}"
          imagePullPolicy: {{ default "" .Values.indexNode.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /esg-search/search
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: ESGF_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: ESGF_DATABASE_HOST
              value: "{{ .Release.Name }}-postgres"
            - name: ESGF_SOLR_INTERNAL_URL
              value: "http://{{ .Release.Name }}-solr:8983"
            - name: ESGF_SOLR_COLLECTION_NUM_SHARDS
              value: "{{ .Values.indexNode.solrNumShards }}"
            - name: ESGF_SOLR_COLLECTION_REPLICATION_FACTOR
              value: "{{ .Values.indexNode.solrReplicationFactor }}"
          resources:
{{ toYaml .Values.indexNode.resources | indent 12 }}
