apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-index-node"
  labels:
{{ include "default-labels" . | indent 4 }}
    component: index-node
spec:
  replicas: {{ .Values.indexNode.replicas }}
  # Select pods on release and component only, rather than all labels
  # This means that the selector will match all pods from all versions of the chart when upgrading
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      component: index-node
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
        component: index-node
      annotations:
        checksum/trust-bundle: {{ include (print $.Template.BasePath "/certificates/trust-bundle-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        # Make sure Solr is up before starting
        - name: ensure-solr-slave
          image: "{{ .Values.solr.image }}:{{ .Values.solr.imageTag }}"
          imagePullPolicy: {{ default "" .Values.solr.imagePullPolicy | quote }}
          args:
            - "wait-for-solr.sh"
            - "--max-attempts"
            - "120"
            - "--solr-url"
            - "http://{{ .Release.Name }}-solr-slave:8983"
      containers:
        - name: index-node
          image: "{{ .Values.indexNode.image }}:{{ .Values.indexNode.imageTag }}"
          imagePullPolicy: {{ default "" .Values.indexNode.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8080
          # The readiness and liveness probes run the same thing, but the liveness
          # probe just waits a while before kicking in whereas the readiness probe
          # starts straight away
          readinessProbe:
            httpGet: &probe
              path: /esg-search/search
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: ESGF_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: ESGF_DATABASE_HOST
              value: "{{ .Release.Name }}-postgres-esgcet"
            - name: ESGF_SOLR_QUERY_URL
              value: "http://{{ .Release.Name }}-solr-slave:8983"
            - name: ESGF_SOLR_PUBLISH_URL
              value: "http://{{ .Release.Name }}-solr-master:8983"
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          resources:
{{ toYaml .Values.indexNode.resources | indent 12 }}
      volumes:
        - name: trust-bundle
          configMap:
            name: "{{ .Release.Name }}-trust-bundle"
